apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deploy:
      kind: DaemonSet
    hostNetwork: true
    dashboard:
      enabled: true
    ports:
      web:
        redirectTo: websecure
    logs:
      level: WARNING
      access:
        enabled: true
    additionalArguments:
      - "--metrics.prometheus=true"

# See https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml for more examples
# The deploy.kind=DaemonSet and hostNetwork=true is to get real ip and x-forwarded for, and can be omitted if this is
# not needed.
